USE TestDB
GO


INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Libby',  'Watson',   24)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Chelsea','Gibbons',  45)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Alfie',  'Stevens',  32)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Holly',  'Webb',    43)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Chelsea','Booth',   55)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Logan',  'Barrett', 29)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Aidan',  'Bell',    87)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('William','Morgan',  73)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Evan',  'Rowe',     37)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Emma M.',  'Arbuckle',23)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Robert ',  'Cook',   45)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Meghan ',  'Simone', 62)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Cleo ',  'Hellman',  43)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Stacy ',  'Beatty',  27)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Joan ',  'Hart',     29)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Juan ',  'Bailey',   27)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Andrew',  'McWilliams',24)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Shawn ',  'Heard',   32)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Cathleen ',  'Moss', 35)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Betty ',  'Villalvazo',51)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Elizabeth',  'Baldwin',23)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Sue ',  'Smith',     55)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Marshall',  'Jones', 51)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Dong ',  'Perry',    52)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Bernard ',  'McKnight',45)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Robert ',  'Toth',   41)
INSERT INTO myschema.Person (FirstName,LastName,Age) 
                   VALUES ('Joesph ',  'Perez',  40)
GO
